name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:     

permissions:
  contents: write 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: Viacheslav1998
          outputs: dist/github-contribution-grid-snake.svg

      - name: Push snake animation to the output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
