name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  
  workflow_dispatch:     
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Generate dark snake (slow + black bg)
        uses: Platane/snk@v3
        with:
          github_user_name: Viacheslav1998
          outputs: |
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&speed=0.3
