name: Generate Snake (Matrix Theme)

on:
  schedule:
    - cron: "0 0 * * *" 
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Generate Matrix Green snake
        uses: Platane/snk@v3
        with:
          github_user_name: Viacheslav1998
          outputs: |
            dist/github-contribution-grid-snake-matrix.svg
          palette: github-dark
          color_snake: "#00FF00"
          color_dots: "#003300,#006600,#009900,#00CC00,#00FF00"

      - name: Push snake animation to the output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
