name: Generate Snake F

on:
  schedule:
    - cron: "0 0 * * *"  
  workflow_dispatch:    

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Generate dark snake (slow + black bg)
        uses: Platane/snk@v3
        with:
          github_user_name: Viacheslav1998
          outputs: |
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&speed=0.3

      - name: Add black background
        run: |
          sed -i 's|<svg width|<svg style="background-color:#000000" width|' dist/github-contribution-grid-snake-dark.svg

      - name: Push snake animation to the output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
