name: Generate Snake F

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate dark snake (slow, solid black background)
        uses: Platane/snk@v3
        with:
          github_user_name: Viacheslav1998
          outputs: |
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&speed=0.3&background=#000000

      - name: Publish snake animation
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
